### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR puts a better link to get the app on F-Droid 👍

### CODE REVIEW

**Comment by corcoran** [comment]
Be aware that this version of hangar is semi deprecated in favor of https://github.com/mimicmobile/hangar 

It would be nice to get that version on fdroid, but since it isn't on Google Play yet either I think there's some work to do.

**Comment by Poussinou** [comment]
Maybe you could merge this PR (because yeah this is the source code of the F-Droid app). you should add at the top of the readme a link to the new version.

Is the package name the same? We will just need to adjust the F-Droid build recipe in that case (if everything is still FLOSS and so on)

**Comment by corcoran** [comment]
The package name Is the same, the reason the new version hasn't entirely replaced this is because it's still missing widgets. The other features (at least in terms of the notification) are all supported however.

At some point I'll add widgets and at that point I can deprecate this version entirely.

One thing of note though is that the new version of Hangar uses Flutter and I haven't looked into the level of support for Flutter in F-Droid.

**Comment by Poussinou** [comment]
We support Flutter at F-Droid as you can see [here](https://gitlab.com/fdroid/rfp/issues?scope=all&utf8=%E2%9C%93&state=closed&label_name[]=flutter). Ping me once you want us to change/update the version in F-Droid, we will then open an Issue on fdroiddata to do it

**Pull request merged**
